name: Automated testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v5
    - uses: xu-cheng/latex-action@v4
      with:
        root_file: |
          tests/test-fa0.tex
          tests/test-fa1.tex
          tests/test-fa5.tex
          tikz-shields-doc.tex
